name: desktoppossystem
description: Core Manager Software.

version: 1.1.80+111
publish_to: none

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  archive: ^4.0.7
  excel:
    git:
      url: https://github.com/justkawal/excel.git
  barcode_widget: ^2.0.4

  dio: ^5.4.3+1

  file_picker: ^10.3.3
  flutter:
    sdk: flutter
  flutter_barcode_listener: ^0.1.4

  # mobile
  mobile_scanner: ^7.1.3
  audio_plus: ^1.0.3

  thermal_printer_plus: ^1.0.11

  flutter_localizations:
    sdk: flutter
  flutter_material_color_picker: ^1.2.0

  flutter_typeahead: ^5.0.1
  font_awesome_flutter: ^10.7.0
  fpdart: ^1.1.0
  gap: ^3.0.1
  image: any
  image_picker: ^1.1.2
  intl: ^0.20.0
  intl_utils: ^2.8.7
  jiffy: ^6.2.1
  loading_indicator:
    path: packages/loading_indicator-master
  month_picker_dialog: ^6.2.3
  open_file: ^3.5.10
  path: any
  path_provider: any
  pdf: ^3.11.3
  rflutter_alert: ^2.0.7
  riverpod_annotation: ^2.6.1
  screenshot: ^3.0.0

  skeletonizer: ^2.0.1

  syncfusion_flutter_charts: ^30.1.42
  syncfusion_flutter_xlsio: ^30.1.42
  toastification: ^3.0.3
  url_launcher: ^6.3.1
  window_manager: ^0.5.0
  flutter_slidable: ^4.0.0

  #database
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.4.0+1
  supabase_flutter: ^2.9.1

  #local storage
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

  #state management
  flutter_riverpod: ^2.6.1

  #encryption
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_swipe_button: ^2.1.3
  desktop_drop: ^0.4.4
  number_to_words_english: ^3.0.4
  device_preview: ^1.3.1
  flutter_screenutil: ^5.9.3

  #printing for bluetooth
  print_bluetooth_thermal: ^1.1.7
  permission_handler: ^11.0.0 # For Bluetooth permissions

  #app restart (mobile only)
  terminate_restart: ^1.0.11

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/db/
    - assets/fonts/
    - assets/sound/

flutter_intl:
  enabled: true
